### PR TITLE
feat!: update ui, standard, microns, social, and harvey ball icons

### PR DESCRIPTION
**Pull request by markcaron**
Updated all the icons from Brand's recent icon updates, including adding a new `microns` set.

### CODE REVIEW

**Comment by markcaron** [comment]
Note: two social icons were missing from this update (email and rss). For now, I've manually fixed these to look as consistent as possible, but they will likely need to be replaced with the official versions in the future.

**Comment by bennypowers** [comment]
I want to improve the preview page a bit
- arrange icons by set
- preview HTML in tooltip a la pf icon docs

Design considerations
- is squared / knockout something that can apply to any icon or only to social?
- are there hard-and-fast rules on how to resize icons when they are in a square?

**Comment by bennypowers** [comment]
Notes from meeting with @ryawilli @amandapearlswig and Michael Wells:
- "icons" have one-and-only-one colour, plus transparency. If it has more than one colour, it's an _illustration_
- social square icons have a specific intent - for buttons. don't use them unless you have a good reason
- non-social icons shouldn't be on circles or squares, generally speaking. just use the icon, don't put it in it's own special container

**Comment by markcaron** [comment]
@bennypowers I'm debating whether making a separate set for `Social Square` icons makes more sense (or not) than simply keeping the square versions of the social media icons under `Social`.

Documentation could still be written to say that designers (and devs) shouldn't use the `-square` versions of the social media icons except for specific instances, like X, Y and Z.

If they're done as separate sets, then I worry about future integrations where the square ones are stored in the same directory/set as the normal ones.

**Comment by bennypowers** [comment]
Whichever you think is better

Did we get more guidance on the name "standard"?

**Comment by markcaron** [comment]
@bennypowers we're moving forward with `Standard` as the directory name (per @ryawilli). So, I think we're good to merge now and move forward with `<rh-icon>`

**Comment by bennypowers** [comment]
@markcaron we still have duplicates of the harvey balls. do they go in standard or in ui?

**Comment by markcaron** [comment]
> do they go in standard or in ui?

Both. The Standard harvey balls are slightly different than the UI ones.

- Standard — thinner line weights, larger viewBox to be used at larger sizes
- UI — thicker line weights, smaller viewBox to be used at smaller sizes

I think we're good to merge now, if that's the only hold up.

**Review by bennypowers — APPROVED** [review]

**Pull request merged**
